name: Deployment template

on:
  workflow_call:
    inputs:
      compose_file:
        description: name of the docker-compose file
        required: true
        type: string
      compose_override_file:
        description: name of the docker-compose override file
        required: true
        type: string
        default: docker-compose.override.yml
      nginx_folder:
        description: folder on the server where nginx config is located
        required: false
        type: string
        default: nginx
      deployment_folder:
        description: folder on the server to deploy to
        required: true
        type: string
      backend_app:
        description: backend application name
        required: false
        type: string
        default: seekretsanta-backend
      frontend_app:
        description: frontend application name
        required: false
        type: string
        default: seekretsanta-frontend
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure deployment directory exists on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/${{ inputs.deployment_folder }}/${{ github.event.repository.name }}
      - name: Create compose overrides
        run: |
          cat > ${{ inputs.compose_override_file }} << EOL
          services:
            backend:
              image: ${{ secrets.DOCKERHUB_USER }}/${{ inputs.backend_app }}:${{ github.sha }}
            frontend:
              image: ${{ secrets.DOCKERHUB_USER }}/${{ inputs.frontend_app }}:${{ github.sha }}
          EOL

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ${{ inputs.compose_override_file }}, ${{ inputs.compose_file }}
          target: "${{ inputs.deployment_folder }}/${{ github.event.repository.name }}/"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/.deploy/${{ github.event.repository.name }}
            docker compose -f ${{ inputs.compose_file }} -f ${{ inputs.compose_override_file }} stop
            docker compose -f ${{ inputs.compose_file }} -f ${{ inputs.compose_override_file }} rm -f
            docker rmi $(docker images -a -q)
            docker compose -f ${{ inputs.compose_file }} -f ${{ inputs.compose_override_file }} pull
            docker compose -f ${{ inputs.compose_file }} -f ${{ inputs.compose_override_file }} up -d
